admins = ["76561198078201908","76561198002511087","76561198002511087"];
DZE_crashLootConfig = [true,2,5,8,0];
CurrencyName = "Coins";
DZE_ATM = ["Infostand_2_EP1"];
LimitOnBank = true;
MaxBankMoney = 100000;
MaxDonatorBankMoney = 500000;
SafeMaxDeposit = 50000;
AllowManualCode = false;
HarderPenalty = true;
MaxHeliCrashes= 5;
dayz_fullMoonNights = true;
MaxVehicleLimit = 5;
DynamicVehicleDamageLow = 60;
DynamicVehicleDamageHigh = 80;
dayz_maxLocalZombies = 3;
dayz_maxGlobalZombiesInit = 5;
dayz_maxZeds = 100;
dayz_sellDistance = 10;
dayz_sellDistance_vehicle = 50;
dayz_sellDistance_boat = 80;
dayz_sellDistance_air = 100;
MaxDynamicDebris = 0;
MaxAmmoBoxes = 5;
MaxMineVeins = 0;
DZE_PlayerZed = false;
DZE_BuildOnRoads = true;
DZE_LootSpawnTimer = 3;
DZE_BackpackGuard = false; 
DZE_requireplot = 1; 
DZE_PlotPole = [45,120];
DZE_checkNearbyRadius = 120;
DZE_StaticConstructionCount = 1;
DZE_ForceNameTags = true;
DZE_R3F_WEIGHT = false;
setViewDistance 1000;
setTerrainGrid 50;
DZE_MissionLootTable = true;
DZE_SelfTransfuse = true;
DZE_selfTransfuse_Values = [6000,5,300];
DZE_ConfigTrader = true;
DZE_DamageBeforeMaint = 0.1;
DZE_vehicleAmmo = 0.2;
DZE_APlotforLife = true;
DZE_PlotOwnership = false;
DZE_modularBuild = true;
DZE_noRotate = ["VaultStorageLocked","WoodLadder_DZ","WoodStairs_DZ","WoodStairsSans_DZ","WoodStairsRails_DZ","VaultStorageLocked","LockboxStorageLocked","Land_HBarrier1_DZ","Lan_HBarrier3_DZ","Land_HBarrier5_DZ","TentStorageDomed","TentStorageDomed2"];
DZE_vectorDegrees = [0.01, 0.1, 1, 5, 15, 45, 90];
DZE_curDegree = 45; 
DZE_dirWithDegrees = true;
DZE_AllowForceSave = true;
DZE_ForceNameTagsInTrader = true;
DZE_Surrender = true;
MaxMineVeins = 10;

ServerIllegalRadius = 200;

GGNoBuildList = [
	"Land_Mil_Barracks",
	"Land_Mil_Barracks_i"
];