
class Category_526 {
class m240_nest_kit { type = "trade_items"; buy[] = {10000,"Coins"}; sell[] = {5000,"Coins"}; };
class Saiga12K { type = "trade_weapons"; buy[] = {450,"Coins"}; sell[] = {345,"Coins"}; }; 
class AKS_GOLD { type = "trade_weapons"; buy[] = {2700,"Coins"}; sell[] = {1725,"Coins"}; };
class m8_compact { type = "trade_weapons"; buy[] = {360,"Coins"}; sell[] = {260,"Coins"}; }; 
class m8_sharpshooter { type = "trade_weapons"; buy[] = {540,"Coins"}; sell[] = {345,"Coins"}; }; 
class m8_holo_sd { type = "trade_weapons"; buy[] = {720,"Coins"}; sell[] = {460,"Coins"}; }; 
class m8_carbine { type = "trade_weapons"; buy[] = {450,"Coins"}; sell[] = {230,"Coins"}; }; 
class M24_des_EP1 { type = "trade_weapons"; buy[] = {900,"Coins"}; sell[] = {660,"Coins"}; }; 
class VSS_vintorez { type = "trade_weapons"; buy[] = {2700,"Coins"}; sell[] = {460,"Coins"}; }; 
class SVD_des_EP1 { type = "trade_weapons"; buy[] = {900,"Coins"}; sell[] = {690,"Coins"}; }; 
class SVD { type = "trade_weapons"; buy[] = {900,"Coins"}; sell[] = {690,"Coins"}; }; 
class DMR { type = "trade_weapons"; buy[] = {2700,"Coins"}; sell[] = {856,"Coins"}; };
class DMR_DZ { type = "trade_weapons"; buy[] = {2700,"Coins"}; sell[] = {856,"Coins"}; };
class DMR_SKN { type = "trade_weapons"; buy[] = {2700,"Coins"}; sell[] = {865,"Coins"}; };
class M8_SAW { type = "trade_weapons"; buy[] = {900,"Coins"}; sell[] = {460,"Coins"}; }; 
class MG36 { type = "trade_weapons"; buy[] = {900,"Coins"}; sell[] = {460,"Coins"}; }; 
class RPK_74 { type = "trade_weapons"; buy[] = {900,"Coins"}; sell[] = {460,"Coins"}; }; 
class M60A4_EP1_DZE { type = "trade_weapons"; buy[] = {1800,"Coins"}; sell[] = {575,"Coins"}; }; 
class m240_scoped_EP1_DZE { type = "trade_weapons"; buy[] = {1800,"Coins"}; sell[] = {690,"Coins"}; }; 
class M249_m145_EP1_DZE { type = "trade_weapons"; buy[] = {1800,"Coins"}; sell[] = {690,"Coins"}; }; 
class MG36_camo { type = "trade_weapons"; buy[] = {900,"Coins"}; sell[] = {460,"Coins"}; }; 
class bizon { type = "trade_weapons"; buy[] = {900,"Coins"}; sell[] = {460,"Coins"}; }; 
class M4A1_HWS_GL_SD_Camo { type = "trade_weapons"; buy[] = {1800,"Coins"}; sell[] = {575,"Coins"}; }; 
class KSVK_DZE { type = "trade_weapons"; buy[] = {27000,"Coins"}; sell[] = {5750,"Coins"}; }; 
class RPG7V { type = "trade_weapons"; buy[] = {45000,"Coins"}; sell[] = {5750,"Coins"}; }; 
class M79_EP1 { type = "trade_weapons"; buy[] = {22500,"Coins"}; sell[] = {4600,"Coins"}; }; 
class M32_EP1 { type = "trade_weapons"; buy[] = {67500,"Coins"}; sell[] = {11500,"Coins"}; };
}; 