
class Category_489 { 
class M9SD { type = "trade_weapons"; buy[] = {200,"Coins"}; sell[] = {100,"Coins"}; }; 
class glock17_EP1 { type = "trade_weapons"; buy[] = {100,"Coins"}; sell[] = {50,"Coins"}; }; 
class Colt1911 { type = "trade_weapons"; buy[] = {20,"Coins"}; sell[] = {10,"Coins"}; }; 
class M9 { type = "trade_weapons"; buy[] = {100,"Coins"}; sell[] = {20,"Coins"}; }; 
class MakarovSD { type = "trade_weapons"; buy[] = {200,"Coins"}; sell[] = {100,"Coins"}; }; 
class revolver_gold_EP1 { type = "trade_weapons"; buy[] = {300,"Coins"}; sell[] = {200,"Coins"}; }; 
class Makarov { type = "trade_weapons"; buy[] = {20,"Coins"}; sell[] = {10,"Coins"}; }; 
class revolver_EP1 { type = "trade_weapons"; buy[] = {20,"Coins"}; sell[] = {10,"Coins"}; };
class RH_Deagleg {type = "trade_weapons";buy[] = {2000,"Coins"};sell[] = {1000,"Coins"};}; 
class RH_Deaglem {type = "trade_weapons";buy[] = {800,"Coins"};sell[] = {400,"Coins"};}; 
class RH_Deaglemz {type = "trade_weapons";buy[] = {1000,"Coins"};sell[] = {500,"Coins"};}; 
class RH_Deaglemzb {type = "trade_weapons";buy[] = {1500,"Coins"};sell[] = {700,"Coins"};}; 
class RH_Deagles {type = "trade_weapons";buy[] = {600,"Coins"};sell[] = {300,"Coins"};}; 
class RH_anac {type = "trade_weapons";buy[] = {600,"Coins"};sell[] = {300,"Coins"};}; 
class RH_anacg {type = "trade_weapons";buy[] = {2000,"Coins"};sell[] = {1000,"Coins"};}; 
class RH_bull {type = "trade_weapons";buy[] = {1000,"Coins"};sell[] = {500,"Coins"};}; 
class RH_python {type = "trade_weapons";buy[] = {700,"Coins"};sell[] = {400,"Coins"};}; 
class RH_browninghp {type = "trade_weapons";buy[] = {300,"Coins"};sell[] = {100,"Coins"};}; 
class RH_p226 {type = "trade_weapons";buy[] = {400,"Coins"};sell[] = {200,"Coins"};}; 
class RH_p226s {type = "trade_weapons";buy[] = {600,"Coins"};sell[] = {300,"Coins"};}; 
class RH_p38 {type = "trade_weapons";buy[] = {400,"Coins"};sell[] = {200,"Coins"};}; 
class RH_ppk {type = "trade_weapons";buy[] = {400,"Coins"};sell[] = {200,"Coins"};}; 
class RH_mk22 {type = "trade_weapons";buy[] = {600,"Coins"};sell[] = {300,"Coins"};}; 
class RH_mk22sd {type = "trade_weapons";buy[] = {700,"Coins"};sell[] = {400,"Coins"};}; 
class RH_mk22v {type = "trade_weapons";buy[] = {500,"Coins"};sell[] = {400,"Coins"};}; 
class RH_mk22vsd {type = "trade_weapons";buy[] = {800,"Coins"};sell[] = {400,"Coins"};}; 
class RH_usp {type = "trade_weapons";buy[] = {600,"Coins"};sell[] = {300,"Coins"};}; 
class RH_uspm {type = "trade_weapons";buy[] = {700,"Coins"};sell[] = {400,"Coins"};}; 
class RH_uspsd {type = "trade_weapons";buy[] = {800,"Coins"};sell[] = {400,"Coins"};}; 
class RH_m1911 {type = "trade_weapons";buy[] = {400,"Coins"};sell[] = {200,"Coins"};}; 
class RH_m1911old {type = "trade_weapons";buy[] = {300,"Coins"};sell[] = {100,"Coins"};}; 
class RH_m1911sd {type = "trade_weapons";buy[] = {600,"Coins"};sell[] = {300,"Coins"};}; 
class RH_tt33 {type = "trade_weapons";buy[] = {600,"Coins"};sell[] = {300,"Coins"};}; 
class RH_mk2 {type = "trade_weapons";buy[] = {600,"Coins"};sell[] = {300,"Coins"};}; 
class RH_m9 {type = "trade_weapons";buy[] = {600,"Coins"};sell[] = {300,"Coins"};}; 
class RH_m93r {type = "trade_weapons";buy[] = {1000,"Coins"};sell[] = {500,"Coins"};}; 
class RH_m9c {type = "trade_weapons";buy[] = {600,"Coins"};sell[] = {300,"Coins"};}; 
class RH_m9csd {type = "trade_weapons";buy[] = {800,"Coins"};sell[] = {400,"Coins"};}; 
class RH_m9sd {type = "trade_weapons";buy[] = {700,"Coins"};sell[] = {400,"Coins"};}; 
class RH_g17 {type = "trade_weapons";buy[] = {600,"Coins"};sell[] = {300,"Coins"};}; 
class RH_g17sd {type = "trade_weapons";buy[] = {700,"Coins"};sell[] = {400,"Coins"};}; 
class RH_g18 {type = "trade_weapons";buy[] = {800,"Coins"};sell[] = {400,"Coins"};}; 
class RH_g19 {type = "trade_weapons";buy[] = {1000,"Coins"};sell[] = {500,"Coins"};}; 
class RH_g19t {type = "trade_weapons";buy[] = {1200,"Coins"};sell[] = {600,"Coins"};}; 
class RH_vz61 {type = "trade_weapons";buy[] = {300,"Coins"};sell[] = {100,"Coins"};}; 
class RH_tec9 {type = "trade_weapons";buy[] = {500,"Coins"};sell[] = {200,"Coins"};}; 
class vil_B_HP {type = "trade_weapons";buy[] = {600,"Coins"};sell[] = {300,"Coins"};}; 
class vil_Glock {type = "trade_weapons";buy[] = {600,"Coins"};sell[] = {300,"Coins"};}; 
class vil_Glock_o {type = "trade_weapons";buy[] = {800,"Coins"};sell[] = {400,"Coins"};}; 
class vil_USP {type = "trade_weapons";buy[] = {600,"Coins"};sell[] = {300,"Coins"};}; 
class vil_USP45 {type = "trade_weapons";buy[] = {700,"Coins"};sell[] = {400,"Coins"};}; 
class vil_USP45SD {type = "trade_weapons";buy[] = {800,"Coins"};sell[] = {400,"Coins"};}; 
class vil_USPSD {type = "trade_weapons";buy[] = {800,"Coins"};sell[] = {400,"Coins"};}; 
class vil_MP5SD_EOTech {type = "trade_weapons";buy[] = {1200,"Coins"};sell[] = {600,"Coins"};}; 
class vil_MP5_EOTech {type = "trade_weapons";buy[] = {1000,"Coins"};sell[] = {500,"Coins"};}; 
class vil_uzi {type = "trade_weapons";buy[] = {600,"Coins"};sell[] = {300,"Coins"};}; 
class vil_uzi_SD {type = "trade_weapons";buy[] = {800,"Coins"};sell[] = {400,"Coins"};}; 
class vil_uzi_c {type = "trade_weapons";buy[] = {700,"Coins"};sell[] = {400,"Coins"};}; 
class vil_uzimini {type = "trade_weapons";buy[] = {600,"Coins"};sell[] = {300,"Coins"};}; 
class vil_uzimini_SD {type = "trade_weapons";buy[] = {800,"Coins"};sell[] = {400,"Coins"};};
 }; 
