class Category_4003 {
class FHQ_ACR_WDL_TWS_SD 		{ type = "trade_weapons"; buy[] = 		{3900,"Coins"}; 	sell[] = {920,"Coins"}; }; 
class FHQ_ACR_WDL_TWS 			{ type = "trade_weapons"; buy[] = 		{2250,"Coins"}; 	sell[] = {575,"Coins"}; }; 
class FHQ_ACR_BLK_TWS_SD 		{ type = "trade_weapons"; buy[] = 		{5500,"Coins"}; 	sell[] = {920,"Coins"}; }; 
class FHQ_ACR_BLK_TWS 			{ type = "trade_weapons"; buy[] = 		{2250,"Coins"}; 	sell[] = {575,"Coins"}; }; 
class FHQ_ACR_TAN_TWS_SD 		{ type = "trade_weapons"; buy[] = 		{5250,"Coins"}; 	sell[] = {920,"Coins"}; }; 
class FHQ_ACR_TAN_TWS 			{ type = "trade_weapons"; buy[] = 		{1800,"Coins"}; 	sell[] = {575,"Coins"}; }; 
class FHQ_ACR_SNW_TWS_SD 		{ type = "trade_weapons"; buy[] = 		{3800,"Coins"}; 	sell[] = {920,"Coins"}; }; 
class FHQ_ACR_SNW_TWS 			{ type = "trade_weapons"; buy[] = 		{1800,"Coins"}; 	sell[] = {575,"Coins"}; }; 
class BAF_LRR_scoped 			{ type = "trade_weapons"; buy[] = 		{31750,"Coins"}; 	sell[] = {10000,"Coins"}; }; 
class BAF_LRR_scoped_W 			{ type = "trade_weapons"; buy[] = 		{32000,"Coins"}; 	sell[] = {10000,"Coins"}; }; 
class USSR_cheytacM200 			{ type = "trade_weapons"; buy[] = 		{59000,"Coins"}; 	sell[] = {28750,"Coins"}; }; 
class USSR_cheytacM200_sd 		{ type = "trade_weapons"; buy[] = 		{37000,"Coins"}; 	sell[] = {15500,"Coins"}; }; 
class m107_DZ 					{ type = "trade_weapons"; buy[] = 		{48000,"Coins"}; 	sell[] = {28000,"Coins"}; };
class BAF_AS50_scoped 			{ type = "trade_weapons"; buy[] = 		{115000,"Coins"}; 	sell[] = {35000,"Coins"}; };
class M110_NVG_EP1 				{ type = "trade_weapons"; buy[] = 		{3300,"Coins"}; 	sell[] = {2300,"Coins"}; };
class KSVK_DZE 					{ type = "trade_weapons"; buy[] = 		{19000,"Coins"}; 	sell[] = {5750,"Coins"}; }; 
class DMR 						{ type = "trade_weapons"; buy[] = 		{900,"Coins"}; 	sell[] = {856,"Coins"}; };
class DMR_DZ 					{ type = "trade_weapons"; buy[] = 		{900,"Coins"}; 	sell[] = {856,"Coins"}; };
class DMR_SKN 					{ type = "trade_weapons"; buy[] = 		{900,"Coins"}; 	sell[] = {865,"Coins"}; };
class Javelin					{ type = "trade_weapons"; buy[] = 		{211500,"Coins"}; 	sell[] = {60000,"Coins"}; };
class Stinger	 				{ type = "trade_weapons"; buy[] = 		{203125,"Coins"}; 	sell[] = {60000,"Coins"}; };
class RPG18	 					{ type = "trade_weapons"; buy[] = 		{183750,"Coins"}; 	sell[] = {60000,"Coins"}; };
};